// Code generated by protoc-gen-go.
// source: github.com/micro/discovery-srv/proto/discovery/discovery.proto
// DO NOT EDIT!

/*
Package go_micro_srv_discovery_discovery is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/discovery-srv/proto/discovery/discovery.proto

It has these top-level messages:
	ServiceEndpoint
	EndpointsRequest
	EndpointsResponse
	HeartbeatsRequest
	HeartbeatsResponse
	WatchResultsRequest
	WatchResultsResponse
*/
package go_micro_srv_discovery_discovery

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_micro_os_discovery "github.com/micro/go-os/discovery/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceEndpoint struct {
	Service  string                          `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Version  string                          `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Endpoint *go_micro_os_discovery.Endpoint `protobuf:"bytes,3,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *ServiceEndpoint) Reset()                    { *m = ServiceEndpoint{} }
func (m *ServiceEndpoint) String() string            { return proto.CompactTextString(m) }
func (*ServiceEndpoint) ProtoMessage()               {}
func (*ServiceEndpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceEndpoint) GetEndpoint() *go_micro_os_discovery.Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type EndpointsRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Limit   uint64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset  uint64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *EndpointsRequest) Reset()                    { *m = EndpointsRequest{} }
func (m *EndpointsRequest) String() string            { return proto.CompactTextString(m) }
func (*EndpointsRequest) ProtoMessage()               {}
func (*EndpointsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EndpointsResponse struct {
	Endpoints []*ServiceEndpoint `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
}

func (m *EndpointsResponse) Reset()                    { *m = EndpointsResponse{} }
func (m *EndpointsResponse) String() string            { return proto.CompactTextString(m) }
func (*EndpointsResponse) ProtoMessage()               {}
func (*EndpointsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EndpointsResponse) GetEndpoints() []*ServiceEndpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type HeartbeatsRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	After  uint64 `protobuf:"varint,2,opt,name=after" json:"after,omitempty"`
	Limit  uint64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *HeartbeatsRequest) Reset()                    { *m = HeartbeatsRequest{} }
func (m *HeartbeatsRequest) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatsRequest) ProtoMessage()               {}
func (*HeartbeatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type HeartbeatsResponse struct {
	Heartbeats []*go_micro_os_discovery.Heartbeat `protobuf:"bytes,1,rep,name=heartbeats" json:"heartbeats,omitempty"`
}

func (m *HeartbeatsResponse) Reset()                    { *m = HeartbeatsResponse{} }
func (m *HeartbeatsResponse) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatsResponse) ProtoMessage()               {}
func (*HeartbeatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HeartbeatsResponse) GetHeartbeats() []*go_micro_os_discovery.Heartbeat {
	if m != nil {
		return m.Heartbeats
	}
	return nil
}

type WatchResultsRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	After   uint64 `protobuf:"varint,2,opt,name=after" json:"after,omitempty"`
	Limit   uint64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset  uint64 `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *WatchResultsRequest) Reset()                    { *m = WatchResultsRequest{} }
func (m *WatchResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchResultsRequest) ProtoMessage()               {}
func (*WatchResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type WatchResultsResponse struct {
	Results []*go_micro_os_discovery.Result `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *WatchResultsResponse) Reset()                    { *m = WatchResultsResponse{} }
func (m *WatchResultsResponse) String() string            { return proto.CompactTextString(m) }
func (*WatchResultsResponse) ProtoMessage()               {}
func (*WatchResultsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *WatchResultsResponse) GetResults() []*go_micro_os_discovery.Result {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*ServiceEndpoint)(nil), "go.micro.srv.discovery.discovery.ServiceEndpoint")
	proto.RegisterType((*EndpointsRequest)(nil), "go.micro.srv.discovery.discovery.EndpointsRequest")
	proto.RegisterType((*EndpointsResponse)(nil), "go.micro.srv.discovery.discovery.EndpointsResponse")
	proto.RegisterType((*HeartbeatsRequest)(nil), "go.micro.srv.discovery.discovery.HeartbeatsRequest")
	proto.RegisterType((*HeartbeatsResponse)(nil), "go.micro.srv.discovery.discovery.HeartbeatsResponse")
	proto.RegisterType((*WatchResultsRequest)(nil), "go.micro.srv.discovery.discovery.WatchResultsRequest")
	proto.RegisterType((*WatchResultsResponse)(nil), "go.micro.srv.discovery.discovery.WatchResultsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Discovery service

type DiscoveryClient interface {
	Endpoints(ctx context.Context, in *EndpointsRequest, opts ...client.CallOption) (*EndpointsResponse, error)
	Heartbeats(ctx context.Context, in *HeartbeatsRequest, opts ...client.CallOption) (*HeartbeatsResponse, error)
	WatchResults(ctx context.Context, in *WatchResultsRequest, opts ...client.CallOption) (*WatchResultsResponse, error)
}

type discoveryClient struct {
	c           client.Client
	serviceName string
}

func NewDiscoveryClient(serviceName string, c client.Client) DiscoveryClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.discovery.discovery"
	}
	return &discoveryClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *discoveryClient) Endpoints(ctx context.Context, in *EndpointsRequest, opts ...client.CallOption) (*EndpointsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Discovery.Endpoints", in)
	out := new(EndpointsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) Heartbeats(ctx context.Context, in *HeartbeatsRequest, opts ...client.CallOption) (*HeartbeatsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Discovery.Heartbeats", in)
	out := new(HeartbeatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) WatchResults(ctx context.Context, in *WatchResultsRequest, opts ...client.CallOption) (*WatchResultsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Discovery.WatchResults", in)
	out := new(WatchResultsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Discovery service

type DiscoveryHandler interface {
	Endpoints(context.Context, *EndpointsRequest, *EndpointsResponse) error
	Heartbeats(context.Context, *HeartbeatsRequest, *HeartbeatsResponse) error
	WatchResults(context.Context, *WatchResultsRequest, *WatchResultsResponse) error
}

func RegisterDiscoveryHandler(s server.Server, hdlr DiscoveryHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Discovery{hdlr}, opts...))
}

type Discovery struct {
	DiscoveryHandler
}

func (h *Discovery) Endpoints(ctx context.Context, in *EndpointsRequest, out *EndpointsResponse) error {
	return h.DiscoveryHandler.Endpoints(ctx, in, out)
}

func (h *Discovery) Heartbeats(ctx context.Context, in *HeartbeatsRequest, out *HeartbeatsResponse) error {
	return h.DiscoveryHandler.Heartbeats(ctx, in, out)
}

func (h *Discovery) WatchResults(ctx context.Context, in *WatchResultsRequest, out *WatchResultsResponse) error {
	return h.DiscoveryHandler.WatchResults(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/micro/discovery-srv/proto/discovery/discovery.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x6b, 0xdb, 0x30,
	0x14, 0x5e, 0x7e, 0x2c, 0x99, 0xdf, 0xc6, 0xb6, 0x68, 0x61, 0x18, 0xc3, 0x58, 0xf0, 0x69, 0x97,
	0x28, 0x2c, 0xd9, 0xb2, 0xc3, 0xa0, 0xf4, 0xd0, 0x42, 0x6f, 0x01, 0x17, 0xda, 0xb3, 0x63, 0x2b,
	0x8e, 0x20, 0xb1, 0x52, 0x49, 0x31, 0xe4, 0x54, 0xe8, 0x3f, 0xde, 0x2a, 0x96, 0xfc, 0xa3, 0x49,
	0x43, 0xe2, 0xd2, 0x9b, 0xde, 0x7b, 0xfe, 0xde, 0xf7, 0x7d, 0xfa, 0x84, 0xe1, 0x2c, 0xa2, 0x72,
	0xbe, 0x9e, 0xe2, 0x80, 0x2d, 0x07, 0x4b, 0x1a, 0x70, 0x36, 0x08, 0xa9, 0x08, 0x58, 0x42, 0xf8,
	0xa6, 0x2f, 0x78, 0x32, 0x58, 0x71, 0x26, 0x4b, 0xbd, 0xe2, 0x84, 0xd3, 0x09, 0xea, 0x45, 0x0c,
	0xa7, 0x38, 0xac, 0xbe, 0xc6, 0xc5, 0x34, 0x3f, 0x39, 0xe3, 0x3d, 0x86, 0x88, 0xf5, 0x99, 0x28,
	0xed, 0xdc, 0xe1, 0xd0, 0x9b, 0xdd, 0x87, 0x1a, 0x7c, 0xb9, 0x26, 0x3c, 0xa1, 0x01, 0xb9, 0x8c,
	0xc3, 0x15, 0xa3, 0xb1, 0x44, 0x36, 0xb4, 0x85, 0x6e, 0xd9, 0xb5, 0x5e, 0xed, 0x97, 0xe5, 0x65,
	0xe5, 0x76, 0xa2, 0xb0, 0x82, 0xb2, 0xd8, 0xae, 0xeb, 0x89, 0x29, 0xd1, 0x7f, 0xf8, 0x40, 0x0c,
	0xde, 0x6e, 0xa8, 0xd1, 0xc7, 0xe1, 0x4f, 0x9c, 0x8b, 0x66, 0xa2, 0xa4, 0x39, 0xa3, 0xf1, 0x72,
	0x80, 0x2b, 0xe1, 0x6b, 0xd6, 0x15, 0x1e, 0xb9, 0x5b, 0x13, 0xf1, 0x3a, 0x11, 0x5d, 0x78, 0xbf,
	0xa0, 0x4b, 0xaa, 0x15, 0x34, 0x3d, 0x5d, 0xa0, 0xef, 0xd0, 0x62, 0xb3, 0x99, 0x20, 0xd2, 0x6e,
	0xa6, 0x6d, 0x53, 0xb9, 0x21, 0x74, 0x4a, 0xac, 0x62, 0xc5, 0x62, 0x41, 0xd0, 0x04, 0xac, 0x4c,
	0x96, 0x50, 0xc4, 0x0d, 0x65, 0xe4, 0x37, 0x3e, 0x76, 0xfb, 0x78, 0xe7, 0x06, 0xbd, 0x62, 0x87,
	0x1b, 0x41, 0xe7, 0x8a, 0xf8, 0x5c, 0x4e, 0x89, 0x5f, 0x98, 0xfb, 0x0c, 0x75, 0x1a, 0x1a, 0x5f,
	0xea, 0xb4, 0x15, 0xee, 0xcf, 0x24, 0xe1, 0xa9, 0x21, 0x25, 0x3c, 0x2d, 0x2a, 0xda, 0xb9, 0x01,
	0x54, 0x26, 0x32, 0x7e, 0xce, 0x01, 0xe6, 0x79, 0xd7, 0x18, 0xea, 0x1d, 0x48, 0x26, 0x87, 0x7b,
	0x25, 0x8c, 0x2b, 0xe0, 0xdb, 0xad, 0x2f, 0x83, 0xb9, 0x5a, 0xb9, 0x5e, 0x9c, 0x92, 0xcf, 0x5b,
	0x98, 0x99, 0x40, 0xf7, 0x39, 0xa9, 0xb1, 0xf3, 0x0f, 0xda, 0x5c, 0xb7, 0x8c, 0x97, 0x1f, 0x07,
	0xbc, 0x68, 0xa0, 0x97, 0x7d, 0x3d, 0x7c, 0xac, 0x83, 0x75, 0x91, 0x4d, 0x51, 0x02, 0x56, 0x1e,
	0x3d, 0x1a, 0x1e, 0xcf, 0x77, 0xf7, 0x75, 0x3a, 0xa3, 0x4a, 0x18, 0x2d, 0xde, 0x7d, 0x87, 0x36,
	0x00, 0x45, 0x46, 0xe8, 0x84, 0x25, 0x7b, 0x4f, 0xc7, 0xf9, 0x53, 0x0d, 0x94, 0x53, 0xdf, 0xc3,
	0xa7, 0xf2, 0x8d, 0xa2, 0xbf, 0xc7, 0xf7, 0xbc, 0x10, 0xbb, 0x33, 0xae, 0x0a, 0xcb, 0x04, 0x4c,
	0x5b, 0xe9, 0x0f, 0x67, 0xf4, 0x14, 0x00, 0x00, 0xff, 0xff, 0x40, 0x3f, 0x27, 0x7e, 0x0c, 0x05,
	0x00, 0x00,
}
