// Code generated by protoc-gen-go.
// source: github.com/micro/discovery-srv/proto/registry/registry.proto
// DO NOT EDIT!

/*
Package go_micro_srv_discovery_registry is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/discovery-srv/proto/registry/registry.proto

It has these top-level messages:
	RegisterRequest
	RegisterResponse
	DeregisterRequest
	DeregisterResponse
	GetServiceRequest
	GetServiceResponse
	ListServicesRequest
	ListServicesResponse
	WatchRequest
	WatchResponse
*/
package go_micro_srv_discovery_registry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_micro_os_discovery "github.com/micro/go-os/discovery/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterRequest struct {
	Service *go_micro_os_discovery.Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterRequest) GetService() *go_micro_os_discovery.Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type RegisterResponse struct {
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DeregisterRequest struct {
	Service *go_micro_os_discovery.Service `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *DeregisterRequest) Reset()                    { *m = DeregisterRequest{} }
func (m *DeregisterRequest) String() string            { return proto.CompactTextString(m) }
func (*DeregisterRequest) ProtoMessage()               {}
func (*DeregisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeregisterRequest) GetService() *go_micro_os_discovery.Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type DeregisterResponse struct {
}

func (m *DeregisterResponse) Reset()                    { *m = DeregisterResponse{} }
func (m *DeregisterResponse) String() string            { return proto.CompactTextString(m) }
func (*DeregisterResponse) ProtoMessage()               {}
func (*DeregisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetServiceRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *GetServiceRequest) Reset()                    { *m = GetServiceRequest{} }
func (m *GetServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*GetServiceRequest) ProtoMessage()               {}
func (*GetServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetServiceRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type GetServiceResponse struct {
	Services []*go_micro_os_discovery.Service `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *GetServiceResponse) Reset()                    { *m = GetServiceResponse{} }
func (m *GetServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*GetServiceResponse) ProtoMessage()               {}
func (*GetServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetServiceResponse) GetServices() []*go_micro_os_discovery.Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type ListServicesRequest struct {
}

func (m *ListServicesRequest) Reset()                    { *m = ListServicesRequest{} }
func (m *ListServicesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListServicesRequest) ProtoMessage()               {}
func (*ListServicesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ListServicesResponse struct {
	Services []*go_micro_os_discovery.Service `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *ListServicesResponse) Reset()                    { *m = ListServicesResponse{} }
func (m *ListServicesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListServicesResponse) ProtoMessage()               {}
func (*ListServicesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ListServicesResponse) GetServices() []*go_micro_os_discovery.Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type WatchRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *WatchRequest) Reset()                    { *m = WatchRequest{} }
func (m *WatchRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()               {}
func (*WatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *WatchRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type WatchResponse struct {
	Result *go_micro_os_discovery.Result `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *WatchResponse) Reset()                    { *m = WatchResponse{} }
func (m *WatchResponse) String() string            { return proto.CompactTextString(m) }
func (*WatchResponse) ProtoMessage()               {}
func (*WatchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *WatchResponse) GetResult() *go_micro_os_discovery.Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.srv.discovery.registry.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.srv.discovery.registry.RegisterResponse")
	proto.RegisterType((*DeregisterRequest)(nil), "go.micro.srv.discovery.registry.DeregisterRequest")
	proto.RegisterType((*DeregisterResponse)(nil), "go.micro.srv.discovery.registry.DeregisterResponse")
	proto.RegisterType((*GetServiceRequest)(nil), "go.micro.srv.discovery.registry.GetServiceRequest")
	proto.RegisterType((*GetServiceResponse)(nil), "go.micro.srv.discovery.registry.GetServiceResponse")
	proto.RegisterType((*ListServicesRequest)(nil), "go.micro.srv.discovery.registry.ListServicesRequest")
	proto.RegisterType((*ListServicesResponse)(nil), "go.micro.srv.discovery.registry.ListServicesResponse")
	proto.RegisterType((*WatchRequest)(nil), "go.micro.srv.discovery.registry.WatchRequest")
	proto.RegisterType((*WatchResponse)(nil), "go.micro.srv.discovery.registry.WatchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Publisher API

type Publisher interface {
	Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error
}

type publisher struct {
	c     client.Client
	topic string
}

func (p *publisher) Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error {
	return p.c.Publish(ctx, p.c.NewPublication(p.topic, msg), opts...)
}

func NewPublisher(topic string, c client.Client) Publisher {
	if c == nil {
		c = client.NewClient()
	}
	return &publisher{c, topic}
}

// Subscriber API

func RegisterSubscriber(topic string, s server.Server, h interface{}, opts ...server.SubscriberOption) error {
	return s.Subscribe(s.NewSubscriber(topic, h, opts...))
}

// Client API for Registry service

type RegistryClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
	Deregister(ctx context.Context, in *DeregisterRequest, opts ...client.CallOption) (*DeregisterResponse, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...client.CallOption) (*GetServiceResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...client.CallOption) (*ListServicesResponse, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...client.CallOption) (Registry_WatchClient, error)
}

type registryClient struct {
	c           client.Client
	serviceName string
}

func NewRegistryClient(serviceName string, c client.Client) RegistryClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.discovery.registry"
	}
	return &registryClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *registryClient) Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Registry.Register", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) Deregister(ctx context.Context, in *DeregisterRequest, opts ...client.CallOption) (*DeregisterResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Registry.Deregister", in)
	out := new(DeregisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...client.CallOption) (*GetServiceResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Registry.GetService", in)
	out := new(GetServiceResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...client.CallOption) (*ListServicesResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Registry.ListServices", in)
	out := new(ListServicesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) Watch(ctx context.Context, in *WatchRequest, opts ...client.CallOption) (Registry_WatchClient, error) {
	req := c.c.NewRequest(c.serviceName, "Registry.Watch", &WatchRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &registryWatchClient{stream}, nil
}

type Registry_WatchClient interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*WatchResponse, error)
}

type registryWatchClient struct {
	stream client.Streamer
}

func (x *registryWatchClient) Close() error {
	return x.stream.Close()
}

func (x *registryWatchClient) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *registryWatchClient) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *registryWatchClient) Recv() (*WatchResponse, error) {
	m := new(WatchResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Registry service

type RegistryHandler interface {
	Register(context.Context, *RegisterRequest, *RegisterResponse) error
	Deregister(context.Context, *DeregisterRequest, *DeregisterResponse) error
	GetService(context.Context, *GetServiceRequest, *GetServiceResponse) error
	ListServices(context.Context, *ListServicesRequest, *ListServicesResponse) error
	Watch(context.Context, *WatchRequest, Registry_WatchStream) error
}

func RegisterRegistryHandler(s server.Server, hdlr RegistryHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Registry{hdlr}, opts...))
}

type Registry struct {
	RegistryHandler
}

func (h *Registry) Register(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.RegistryHandler.Register(ctx, in, out)
}

func (h *Registry) Deregister(ctx context.Context, in *DeregisterRequest, out *DeregisterResponse) error {
	return h.RegistryHandler.Deregister(ctx, in, out)
}

func (h *Registry) GetService(ctx context.Context, in *GetServiceRequest, out *GetServiceResponse) error {
	return h.RegistryHandler.GetService(ctx, in, out)
}

func (h *Registry) ListServices(ctx context.Context, in *ListServicesRequest, out *ListServicesResponse) error {
	return h.RegistryHandler.ListServices(ctx, in, out)
}

func (h *Registry) Watch(ctx context.Context, stream server.Streamer) error {
	m := new(WatchRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.RegistryHandler.Watch(ctx, m, &registryWatchStream{stream})
}

type Registry_WatchStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*WatchResponse) error
}

type registryWatchStream struct {
	stream server.Streamer
}

func (x *registryWatchStream) Close() error {
	return x.stream.Close()
}

func (x *registryWatchStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *registryWatchStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *registryWatchStream) Send(m *WatchResponse) error {
	return x.stream.Send(m)
}

func init() {
	proto.RegisterFile("github.com/micro/discovery-srv/proto/registry/registry.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x4b, 0xfb, 0x30,
	0x18, 0xc7, 0x57, 0x7e, 0x3f, 0xe7, 0x7c, 0x9c, 0xe8, 0xe2, 0x84, 0x51, 0x50, 0x47, 0x4f, 0xbb,
	0x34, 0x9d, 0x9b, 0x13, 0x11, 0x8f, 0xa2, 0x07, 0x15, 0x24, 0x1e, 0x3c, 0xbb, 0x1a, 0xba, 0x8a,
	0x33, 0x5b, 0x9e, 0xac, 0xb2, 0x83, 0x6f, 0xd4, 0x57, 0x23, 0x64, 0xe9, 0x9f, 0x59, 0xa5, 0x1d,
	0xec, 0x96, 0x86, 0xef, 0xf3, 0xfd, 0xa4, 0xcd, 0x87, 0xc2, 0x65, 0x10, 0xaa, 0xd1, 0x6c, 0x48,
	0x7d, 0x31, 0xf6, 0xc6, 0xa1, 0x2f, 0x85, 0xf7, 0x12, 0xa2, 0x2f, 0x22, 0x2e, 0xe7, 0x2e, 0xca,
	0xc8, 0x9b, 0x48, 0xa1, 0x84, 0x27, 0x79, 0x10, 0xa2, 0x92, 0xf3, 0x64, 0x41, 0xf5, 0x3e, 0x39,
	0x0e, 0x04, 0xd5, 0x53, 0x14, 0x65, 0x44, 0x93, 0x49, 0x1a, 0xc7, 0xec, 0xb3, 0x5c, 0x7d, 0x20,
	0x5c, 0x81, 0x29, 0xc4, 0x00, 0xd2, 0x51, 0xfd, 0xec, 0xdc, 0xc2, 0x2e, 0xd3, 0x1d, 0x5c, 0x32,
	0x3e, 0x9d, 0x71, 0x54, 0xe4, 0x1c, 0x36, 0x91, 0xcb, 0x28, 0xf4, 0x79, 0xcb, 0x6a, 0x5b, 0x9d,
	0xed, 0xde, 0x11, 0x4d, 0xe8, 0x02, 0x33, 0xf0, 0xc7, 0x45, 0x8a, 0xc5, 0x71, 0x87, 0xc0, 0x5e,
	0x5a, 0x86, 0x13, 0xf1, 0x8e, 0xdc, 0xb9, 0x87, 0xc6, 0x15, 0x97, 0x6b, 0x43, 0x34, 0x81, 0x64,
	0xeb, 0x0c, 0xc4, 0x85, 0xc6, 0x0d, 0x57, 0x71, 0xd8, 0x40, 0x5a, 0xcb, 0x90, 0xad, 0xb4, 0xe4,
	0x01, 0x48, 0x36, 0xbe, 0x28, 0x21, 0x17, 0x50, 0x33, 0x01, 0x6c, 0x59, 0xed, 0x7f, 0x25, 0x4e,
	0x95, 0xe4, 0x9d, 0x03, 0xd8, 0xbf, 0x0b, 0x31, 0xae, 0x44, 0x73, 0x04, 0x87, 0x41, 0x73, 0x79,
	0x7b, 0x0d, 0xa8, 0x0e, 0xd4, 0x9f, 0x9e, 0x95, 0x3f, 0x2a, 0x7e, 0xcd, 0x6b, 0xd8, 0x31, 0x49,
	0x83, 0x1d, 0x40, 0x55, 0x72, 0x9c, 0xbd, 0x29, 0xf3, 0xd5, 0x0f, 0xff, 0x80, 0x32, 0x1d, 0x62,
	0x26, 0xdc, 0xfb, 0xfa, 0x0f, 0x35, 0x66, 0x44, 0x23, 0xd3, 0x78, 0xcd, 0x25, 0xe9, 0xd2, 0x02,
	0x2d, 0xe9, 0x0f, 0xb7, 0xec, 0x93, 0x15, 0x26, 0xcc, 0xdd, 0x56, 0xc8, 0x07, 0x40, 0x7a, 0xe7,
	0xa4, 0x57, 0x58, 0x91, 0xf3, 0xcd, 0xee, 0xaf, 0x34, 0x93, 0x05, 0xa7, 0x9e, 0x94, 0x00, 0xe7,
	0x1c, 0x2c, 0x01, 0xce, 0x8b, 0xe8, 0x54, 0xc8, 0x27, 0xd4, 0xb3, 0xde, 0x90, 0xd3, 0xc2, 0x9a,
	0x5f, 0xec, 0xb3, 0x07, 0x2b, 0x4e, 0x25, 0xf8, 0x57, 0xd8, 0xd0, 0xe2, 0x10, 0xb7, 0xb0, 0x21,
	0xab, 0xa2, 0x4d, 0xcb, 0xc6, 0x63, 0x52, 0xd7, 0x1a, 0x56, 0xf5, 0x7f, 0xa8, 0xff, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x5d, 0x89, 0xb5, 0xe8, 0x20, 0x05, 0x00, 0x00,
}
